on:
  push:
    branches:
      - main
  workflow_dispatch: {}
      
jobs:
  build-site:
    runs-on: [cms-runners]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build site
        run: pnpm run build
      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.lab.verysmart.house
          username: "robot$images+gha"
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Image
        shell: bash
        working-directory: image
        run: |
          pack build registry.lab.verysmart.house/images/cms --publish --buildpack paketo-buildpacks/nginx --builder paketobuildpacks/builder-jammy-base
      