on:
  push:
    branch: main
 
jobs:
  build-site:
    runs-on: [cms-runners]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.lab.verysmart.house
          username: "robot$images+gha"
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Image
        shell: bash
        run: |
          pack build registry.lab.verysmart.house/images/cms --publish --buildpack paketo-buildpacks/nginx --builder paketobuildpacks/builder-jammy-base
